services:
  server:
    build:
      context: ./server
      target: dev
    ports:
      - 3000:3000
    volumes:
      - ./server/src:/opt/app

  client:
    build:
      context: ./client
      target: final
    volumes:
      - ./client/src:/opt/app
    ports:
      - 8080:8080
