services:
  server:
    build:
      context: ./server
      target: dev
    ports:
      - 3000:3000
    volumes:
      - ./server/src:/opt/app

  client:
    build:
      context: ./client
      target: final
    volumes:
      - type: bind
        source: ./client/src
        target: /opt/app
      - type : volume
        source: node_modules
        target: /opt/app/node_modules
    ports:
      - 8080:8080
volumes:
  node_modules: